#version: 0.0.1
#@edt M06 2018-2019
#ldapserver practica LDAP+PAM edt.org
#----------------------
FROM fedora:27
LABEL author="@edt ASIX M06 Curs 2018-2019"
LABEL description="ldapserver edt.org practica LDAP+PAM"
RUN dnf -y install procps openldap-clients openldap-servers vim procps less tree nmap mlocate man telnet iproute
RUN mkdir /opt/docker
COPY * /opt/docker/
RUN cp /opt/docker/ldap.conf /etc/openldap/ldap.conf
RUN chmod +x /opt/docker/install.sh /opt/docker/startup.sh
CMD ["/opt/docker/startup.sh"]
EXPOSE 389
WORKDIR /opt/docker

